apiVersion: tekton.dev/v1
kind: Pipeline
metadata:

  name: quarkus-jvm-helloworld

spec:

  tasks:

    - name: clone-project
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'true'
        - name: URL
          value: 'https://github.com/mukesh1327/quarkus-apps.git'
        - name: REVISION
          value: main
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: 01-Quarkus-Hello-World
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: source-code


    - name: unit-test
      params:
        - name: GOALS
          value:
            - test
        - name: MAVEN_MIRROR_URL
          value: ''
        - name: SUBDIRECTORY
          value: 01-Quarkus-Hello-World
      runAfter:
        - clone-project
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: maven
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: source-code
        - name: maven_settings
          workspace: maven-packages


    - name: maven-package
      params:
        - name: GOALS
          value:
            - package
        - name: MAVEN_MIRROR_URL
          value: ''
        - name: SUBDIRECTORY
          value: 01-Quarkus-Hello-World
      runAfter:
        - unit-test
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: maven
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: source-code
        - name: maven_settings
          workspace: maven-packages


    - name: buildah-docker-jvm
      params:
        - name: IMAGE
          value: quay.io/mukeshs1306/quarkus-helloworld
        - name: DOCKERFILE
          value: ./src/main/docker/Dockerfile.jvm
        - name: BUILD_ARGS
          value: []
        - name: CONTEXT
          value: 01-Quarkus-Hello-World
        - name: STORAGE_DRIVER
          value: vfs
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
        - name: TLS_VERIFY
          value: 'true'
        - name: VERBOSE
          value: 'false'
      runAfter:
        - maven-package
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: source-code

  workspaces:
    - name: source-code
    - name: maven-packages
