apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkus-jvm-helloworld.fullname" . }}
  labels:
    {{- include "quarkus-jvm-helloworld.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPortName }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "quarkus-jvm-helloworld.selectorLabels" . | nindent 4 }}
