kind: Secret
apiVersion: v1
metadata:
  name: git-repo
  namespace: openshift-gitops

  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io

data:
  password: git-pat-base64             # change-it
  project: gitops-project-name-base64  # project created in ArgoCD not openshift project
  type: Z2l0                           # git
  url: giturl-base64                   # change-it
  username: git-username-base64        # change-it
type: Opaque
