kind: PersistentVolumeClaim
apiVersion: v1
metadata:

  name: manifests-workspace

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

  # storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem

