kind: Secret
apiVersion: v1
metadata:
  name: image-registry

  annotations:
    tekton.dev/docker-0: 'https://quay.io/'

data:
  .dockerconfigjson: auth.json | base64
type: kubernetes.io/dockerconfigjson
